### ISSUE TITLE
"fromShortName, fromLongName and fromHardware: unknown" if "from" field is 8 characters instead of 9

### ISSUE THREAD

**Issue by Kollensperger** [scruplelesswizard/meshtastic-node-red#1]
Hi @scruplelesswizard and thanks again for your excellent effort in this. This structured overview has just made using node-red with meshtastic so much easier.

I'm not quite sure if this is the right place to post, but I noticed when using e.g. the write Position Measurement InfluxDB that some of the payloads for some of my nodes do not populate the names correctly, whilst others do.

The fields fromShortName, fromLongName and fromHardware all remain "unknown" for some nodes.

The common denominator for those that populate these fields correctly is that the "from" field is 9 characters long, e.g. !ald3da42
whilst those that remain "unknown" all are 8 characters long, e.g. !f356270

This holds true for all nodes I've tested (3 with 9 characters and 3 with 8).

**Comment by scruplelesswizard** [comment]
Hi @Kollensperger, thank you for this report! I'll have a pull request up shortly to fix this
